sonata_seo:
    encoding: UTF-8
    page:
        title: "Bus Transporte Guatemala | Transporte Fuente del Norte"
        # title_prefix:  'Prefix |'
        # title_suffix:  '| Suffix'
        default: sonata.seo.page.default
        metas:
            name:
                keywords: bus transporte boleto pasajero pasaje guatemala
                description: Empresa de buses para servicio de transporte de pasajeros en Guatemala. Ofrecemos compra de pasaje online y un servicio de calidad a nuestros clientes, una fuente de trabajo estable para nuestros empleados, beneficio para el desarrollo social y económico del país; basado en la eficiencia y actitudes orientadas a la satisfacción del cliente y a la mejora continua.
                robots: index, follow

            property:
                # Facebook application settings
                #'fb:app_id':          XXXXXX
                #'fb:admins':          admin1, admin2

                # Open Graph information
                # see http://developers.facebook.com/docs/opengraphprotocol/#types or http://ogp.me/
                "og:site_name": Transporte Fuente del Norte
                "og:description": Empresa de buses para servicio de transporte de pasajeros en Guatemala. Ofrecemos compra de pasaje online.

            http-equiv:
                "Content-Type": text/html; charset=utf-8
                #'X-Ua-Compatible':      IE=EmulateIE7

            charset:
                UTF-8: ""

        head:
            "xmlns": http://www.w3.org/1999/xhtml
            "xmlns:og": http://opengraphprotocol.org/schema/
            #'xmlns:fb':           "http://www.facebook.com/2008/fbml"
