version: "3.4"

# Production environment override
services:
  php:
    volumes:
      - ./:/srv/app
    environment:
      APP_SECRET: ${APP_SECRET}
      MERCURE_JWT_SECRET: ${CADDY_MERCURE_JWT_SECRET}

  caddy:
    volumes:
      - ./public:/srv/app/public:ro
    environment:
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
