doctrine:
    orm:
        entity_managers:
            default:
                second_level_cache:
                    enabled: true
                    region_lifetime: 864000
                    region_cache_driver:
                        type: pool
                        pool: doctrine.second_level_cache_pool
framework:
    cache:
        pools:
            doctrine.second_level_cache_pool:
                adapter: cache.app
